[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Good practice for SPAs. Not strictly required here (no router),
# but harmless and future-proof.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200